apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appstudio-mgmt-argocd
rules:
- apiGroups:
  - ''
  resources:
  - ConfigMap
  - Namespace
  - Secret
  - Service
  - ServiceAccount
  verbs:
  - '*'
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - MutatingWebhookConfiguration
  - ValidatingWebhookConfiguration
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - CustomResourceDefinition
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - Deployment
  - StatefulSet
  verbs:
  - '*'
- apiGroups:
  - appstudio.redhat.com
  resources:
  - BuildPipelineSelector
  - DeploymentTargetClass
  - EnterpriseContractPolicy
  verbs:
  - '*'
- apiGroups:
  - argoproj.io
  resources:
  - Application
  - ArgoCD
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - CronJob
  - Job
  verbs:
  - '*'
- apiGroups:
  - console.openshift.io
  resources:
  - ConsoleYAMLSample
  verbs:
  - '*'
- apiGroups:
  - external-secrets.io
  resources:
  - ClusterSecretStore
  - ExternalSecret
  verbs:
  - '*'
- apiGroups:
  - grafana.integreatly.org
  resources:
  - Grafana
  - GrafanaDashboard
  - GrafanaDatasource
  verbs:
  - '*'
- apiGroups:
  - jvmbuildservice.io
  resources:
  - SystemConfig
  verbs:
  - '*'
- apiGroups:
  - keycloak.org
  resources:
  - Keycloak
  - KeycloakRealm
  verbs:
  - '*'
- apiGroups:
  - logging.openshift.io
  resources:
  - ClusterLogForwarder
  - ClusterLogging
  verbs:
  - '*'
- apiGroups:
  - minio.min.io
  resources:
  - Tenant
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - ServiceMonitor
  verbs:
  - '*'
- apiGroups:
  - monitoring.rhobs
  resources:
  - MonitoringStack
  - ServiceMonitor
  verbs:
  - '*'
- apiGroups:
  - networking.k8s.io
  resources:
  - NetworkPolicy
  verbs:
  - '*'
- apiGroups:
  - oadp.openshift.io
  resources:
  - DataProtectionApplication
  verbs:
  - '*'
- apiGroups:
  - operator.external-secrets.io
  resources:
  - OperatorConfig
  verbs:
  - '*'
- apiGroups:
  - operator.tekton.dev
  resources:
  - TektonConfig
  verbs:
  - '*'
- apiGroups:
  - operators.coreos.com
  resources:
  - CatalogSource
  - OperatorGroup
  - Subscription
  verbs:
  - '*'
- apiGroups:
  - pipelinesascode.tekton.dev
  resources:
  - Repository
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - ClusterRole
  - ClusterRoleBinding
  - Role
  - RoleBinding
  verbs:
  - '*'
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - GroupSync
  verbs:
  - '*'
- apiGroups:
  - route.openshift.io
  resources:
  - Route
  verbs:
  - '*'
- apiGroups:
  - security.openshift.io
  resources:
  - SecurityContextConstraints
  verbs:
  - '*'
- apiGroups:
  - tekton.dev
  resources:
  - Task
  verbs:
  - '*'
- apiGroups:
  - velero.io
  resources:
  - Schedule
  verbs:
  - '*'
